"""Add notification_enabled to User model

Revision ID: 100fe936530b
Revises: 2bbbe09aa3bc
Create Date: 2025-08-21 17:21:31.504402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100fe936530b'
down_revision = '2bbbe09aa3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_enabled')

    # ### end Alembic commands ###
