"""Update todo due_date to DateTime and add meeting_task_id foreign key

Revision ID: 66594349a4c4
Revises: 7ab1b25a92b8
Create Date: 2025-07-26 14:10:31.119731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66594349a4c4'
down_revision = '7ab1b25a92b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_task', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_meeting_task_todo_id'), ['todo_id'])
        batch_op.create_foreign_key(batch_op.f('fk_meeting_task_todo_id_todo'), 'todo', ['todo_id'], ['id'])

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_todo_meeting_task_id_meeting_task'), 'meeting_task', ['meeting_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_todo_meeting_task_id_meeting_task'), type_='foreignkey')
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('meeting_task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meeting_task_todo_id_todo'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_meeting_task_todo_id'), type_='unique')

    # ### end Alembic commands ###
