"""Add ScheduledNotification model

Revision ID: 7315ea1f17d6
Revises: faa6082528a2
Create Date: 2025-09-11 15:44:09.129138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7315ea1f17d6'
down_revision = 'faa6082528a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('recipient_user_ids', sa.String(length=500), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('specific_time', sa.Time(), nullable=False),
    sa.Column('weekly_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_scheduled_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_notification'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_notification')
    # ### end Alembic commands ###
