"""Allow nullable discussion_item_id in MeetingTask and remove cascade delete from DiscussionItem

Revision ID: 7ab1b25a92b8
Revises: 
Create Date: 2025-07-26 14:07:27.071820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab1b25a92b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_task', schema=None) as batch_op:
        batch_op.alter_column('discussion_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

        batch_op.create_foreign_key(batch_op.f('fk_meeting_task_discussion_item_id'), 'discussion_item', ['discussion_item_id'], ['id'], ondelete='SET NULL')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('meeting_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_meeting_task_discussion_item_id'), 'discussion_item', ['discussion_item_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('discussion_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
