"""Add manager_id and ReportSchedule

Revision ID: 9e5c74542ec0
Revises: 100fe936530b
Create Date: 2025-09-09 20:21:13.867758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5c74542ec0'
down_revision = '100fe936530b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('schedule_day', sa.Integer(), nullable=False),
    sa.Column('schedule_time', sa.Time(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], name=op.f('fk_report_schedule_manager_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_schedule'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_manager_id_user'), 'user', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_manager_id_user'), type_='foreignkey')
        batch_op.drop_column('manager_id')

    op.drop_table('report_schedule')
    # ### end Alembic commands ###
