"""Add require_next_week_tasks to ReportSchedule

Revision ID: faa6082528a2
Revises: 9e5c74542ec0
Create Date: 2025-09-11 14:38:17.451007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa6082528a2'
down_revision = '9e5c74542ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_next_week_tasks', sa.Boolean(), nullable=True))

    # Update existing rows to set a default value (False)
    op.execute('UPDATE report_schedule SET require_next_week_tasks = FALSE WHERE require_next_week_tasks IS NULL')

    with op.batch_alter_table('report_schedule', schema=None) as batch_op:
        batch_op.alter_column('require_next_week_tasks',
                              existing_type=sa.Boolean(),
                              nullable=False,
                              existing_nullable=True) # Set to NOT NULL

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_schedule', schema=None) as batch_op:
        batch_op.drop_column('require_next_week_tasks')

    # ### end Alembic commands ###
